### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [yyfrankyy/dns-over-http2#1]
npm install request spdy dnsd

installing depend as package.js http2": "^3.3.6 didnt solve. it keeps asking for spdy.

```

`PS C:\app\dns-over-http2-master> node.exe .\index.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'dnsd'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\app\dns-over-http2-master\index.js:1:76)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
PS C:\app\dns-over-http2-master> npm install dnsd
dns-over-http2@1.0.0 C:\app\dns-over-http2-master
`-- dnsd@0.9.6
  +-- defaultable@0.7.2
  `-- optimist@0.3.7
    `-- wordwrap@0.0.3

PS C:\app\dns-over-http2-master> node.exe .\index.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'spdy'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\app\dns-over-http2-master\index.js:2:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
PS C:\app\dns-over-http2-master> npm install http2
dns-over-http2@1.0.0 C:\app\dns-over-http2-master
`-- http2@3.3.6

PS C:\app\dns-over-http2-master> node.exe .\index.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'spdy'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\app\dns-over-http2-master\index.js:2:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
PS C:\app\dns-over-http2-master> npm install spdy
dns-over-http2@1.0.0 C:\app\dns-over-http2-master
`-- spdy@3.4.3
  +-- debug@2.2.0
  | `-- ms@0.7.1
  +-- handle-thing@1.2.5
  +-- http-deceiver@1.2.7
  +-- select-hose@2.0.0
  `-- spdy-transport@2.0.15
    +-- hpack.js@2.1.6
    | `-- inherits@2.0.3
    +-- obuf@1.1.1
    +-- readable-stream@2.1.5
    | +-- buffer-shims@1.0.0
    | +-- core-util-is@1.0.2
    | +-- isarray@1.0.0
    | +-- process-nextick-args@1.0.7
    | +-- string_decoder@0.10.31
    | `-- util-deprecate@1.0.2
    `-- wbuf@1.7.2
      `-- minimalistic-assert@1.0.0

PS C:\app\dns-over-http2-master> node.exe .\index.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\app\dns-over-http2-master\index.js:3:36)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
PS C:\app\dns-over-http2-master> npm install request
dns-over-http2@1.0.0 C:\app\dns-over-http2-master
`-- request@2.75.0
  +-- aws-sign2@0.6.0
  +-- aws4@1.4.1
  +-- bl@1.1.2
  | `-- readable-stream@2.0.6
  +-- caseless@0.11.0
  +-- combined-stream@1.0.5
  | `-- delayed-stream@1.0.0
  +-- extend@3.0.0
  +-- forever-agent@0.6.1
  +-- form-data@2.0.0
  | `-- asynckit@0.4.0
  +-- har-validator@2.0.6
  | +-- chalk@1.1.3
  | | +-- ansi-styles@2.2.1
  | | +-- escape-string-regexp@1.0.5
  | | +-- has-ansi@2.0.0
  | | | `-- ansi-regex@2.0.0
  | | +-- strip-ansi@3.0.1
  | | `-- supports-color@2.0.0
  | +-- commander@2.9.0
  | | `-- graceful-readlink@1.0.1
  | +-- is-my-json-valid@2.14.0
  | | +-- generate-function@2.0.0
  | | +-- generate-object-property@1.2.0
  | | | `-- is-property@1.0.2
  | | +-- jsonpointer@2.0.0
  | | `-- xtend@4.0.1
  | `-- pinkie-promise@2.0.1
  |   `-- pinkie@2.0.4
  +-- hawk@3.1.3
  | +-- boom@2.10.1
  | +-- cryptiles@2.0.5
  | +-- hoek@2.16.3
  | `-- sntp@1.0.9
  +-- http-signature@1.1.1
  | +-- assert-plus@0.2.0
  | +-- jsprim@1.3.1
  | | +-- extsprintf@1.0.2
  | | +-- json-schema@0.2.3
  | | `-- verror@1.3.6
  | `-- sshpk@1.10.1
  |   +-- asn1@0.2.3
  |   +-- assert-plus@1.0.0
  |   +-- bcrypt-pbkdf@1.0.0
  |   +-- dashdash@1.14.0
  |   | `-- assert-plus@1.0.0
  |   +-- ecc-jsbn@0.1.1
  |   +-- getpass@0.1.6
  |   | `-- assert-plus@1.0.0
  |   +-- jodid25519@1.0.2
  |   +-- jsbn@0.1.0
  |   `-- tweetnacl@0.14.3
  +-- is-typedarray@1.0.0
  +-- isstream@0.1.2
  +-- json-stringify-safe@5.0.1
  +-- mime-types@2.1.12
  | `-- mime-db@1.24.0
  +-- node-uuid@1.4.7
  +-- oauth-sign@0.8.2
  +-- qs@6.2.1
  +-- stringstream@0.0.5
  +-- tough-cookie@2.3.1
  `-- tunnel-agent@0.4.3

PS C:\app\dns-over-http2-master> node.exe .\index.js
{ Error: bind EACCES 127.0.0.1:5353
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'bind',
  address: '127.0.0.1',
  port: 5353 }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN dns.google.com:443
    at Object.exports._errnoException (util.js:1036:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by yyfrankyy** [comment]
fixed. https://github.com/yyfrankyy/dns-over-http2/commit/eedc3a7977f4f5b51983fe8e26f3125a9db3f2f1
