### ISSUE TITLE
cannot set timeout argv  

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [yyfrankyy/dns-over-http2#23]
node .\h2dns -t 5000
node .\h2dns --timeout 5000

```

TypeError: "msecs" argument must be a number
    at Object.exports.enroll (timers.js:298:11)
    at Socket.setTimeout (net.js:330:12)
    at ClientRequest.<anonymous> (_http_client.js:642:10)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at tickOnSocket (_http_client.js:567:7)
    at onSocketNT (_http_client.js:579:5)
---------------------------------------------
    at ClientRequest.setTimeout (_http_client.js:641:8)
    at Request.start (C:\app\yyfrankyy\node_modules\request\request.js:773:16)
    at Request.end (C:\app\yyfrankyy\node_modules\request\request.js:1398:10)
    at end (C:\app\yyfrankyy\node_modules\request\request.js:567:14)
    at Immediate.<anonymous> (C:\app\yyfrankyy\node_modules\request\request.js:581:7)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

parseInt?

**Comment by Opensourcecommunitydevelopment** [comment]
fixed in: https://github.com/yyfrankyy/h2dns/pull/22
