### ISSUE TITLE
Still keep getting Error: Can't send request after GOAWAY

### ISSUE THREAD

**Issue by yyfrankyy** [yyfrankyy/dns-over-http2#5]
https://github.com/indutny/node-spdy/issues/278

**Comment by Opensourcecommunitydevelopment** [comment]
me too

```
`agent error: Error: Can't send request after GOAWAY
request error Error: socket hang up
Error: Can't send request after GOAWAY
    at Connection.reserveStream (C:\app\dns-over-http2-master\node_modules\spdy-transport\lib\spdy-transport\connection.js:612:15)
    at Agent._createStream (C:\app\dns-over-http2-master\node_modules\spdy\lib\spdy\agent.js:228:27)
    at Handle.<anonymous> (C:\app\dns-over-http2-master\node_modules\spdy\lib\spdy\agent.js:186:29)
    at Handle.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Handle.emit (events.js:185:7)
    at ClientRequest.send (C:\app\dns-over-http2-master\node_modules\spdy\lib\spdy\handle.js:133:10)
    at ClientRequest.OutgoingMessage.end (_http_outgoing.js:600:16)
    at Request.end (C:\app\dns-over-http2-master\node_modules\request\request.js:1401:14)
    at end (C:\app\dns-over-http2-master\node_modules\request\request.js:567:14)
Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at TLSWrap.onread (net.js:564:26)
request error Error: New stream after GOAWAY
Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at TLSWrap.onread (net.js:564:26)
```

**Comment by Opensourcecommunitydevelopment** [comment]
just thinking, how about workaround for Connection loss; drop or goaway by Holding a second Keep-alive and Go To use it for next request once the Primary is having error. After this Force close first Connection and make secondary Primary. Than open another secondary Connection for fallback andOr Backup. Keep-alive by the ping function:-)
